# Generated by Django 4.1.1 on 2022-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateField()),
                ('returns', models.FloatField()),
                ('equity_id', models.CharField(max_length=5)),
                ('open_v', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
            ],
        ),
    ]
